### ISSUE TITLE
Off-Topic

### ISSUE THREAD

**Issue by ARBoyGo** [lukeorth/poison#102]
I want to show TOC in my [about page](https://arboy.is-a.dev/about/).

**Comment by ARBoyGo** [comment]
Just give some idea.

**Comment by ARBoyGo** [comment]
@lukeorth, I updated the about page like we do the post. It kinda work. 
But not really a good idea. 
Here is the commit. 
https://github.com/ARBoyGo/arboygo.github.io/commit/dffd5b1180b594f3fededf8111d1a565ed957ca4

**Comment by ARBoyGo** [comment]
You'll see anchor heading trying to add it. as well.

**Comment by lukeorth** [comment]
Hi @ARBoyGo, sorry for my delayed reply.  

I took a look at your [arboygo.github.io](https://github.com/ARBoyGo/arboygo.github.io) repo and submitted a [PR](https://github.com/ARBoyGo/arboygo.github.io/pull/1) with some changes.  You've done a lot of good work in there, but the problem is that your `poison-mod` theme differs from the `poison` theme.  While that's not _technically_ an issue, it does mean that it'll be extremely difficult to pull in any updates that I make to `poison` in the future.  If that's not a big deal to you (and it may not be if you're happy with what you have), then what you have is fine.  However, if you like the `poison` theme and want to incorporate future changes, the best strategy is to leave the theme untouched and simply override the portions of the theme that you want changed.

For example, if you want the Table of Contents to show in your About page, you can override this by creating a `layouts/about/about.html` within your project (so not in the `/themes/` directory) that overrides what I have in the `poison` theme.  Hopefully that makes sense after looking at my PR.

Again, please don't feel pressured to merge my code if you like what you have.  I just wanted to provide you with the option to continue receiving updates from `poison` and clarify how themes are typically used and modified in Hugo. :slightly_smiling_face:

**Comment by ARBoyGo** [comment]
Thanks I understand.
