### ISSUE TITLE
Sections disappear if _index.md contains title with space in it

### ISSUE THREAD

**Issue by UppaJung** [lukeorth/poison#118]
A title with a space in the `_index.md` of a section (e.g., "About Me" rather than "About") causes the entire section not to be rendered.

**Comment by lukeorth** [comment]
@UppaJung, sorry for my delay in getting to this issue.  Thank you for reporting this!

I updated the menu logic and confirmed that the issue is fixed (screenshots below).

_Demo site screenshot_
![image](https://github.com/lukeorth/poison/assets/35306887/a4f4ac25-12f4-4ea4-bc6b-15c4ff150927)

_toml.config_
![image](https://github.com/lukeorth/poison/assets/35306887/b9da9551-625a-41b7-b4cc-6fdefc66adb5)

_Section structure_
![image](https://github.com/lukeorth/poison/assets/35306887/918c064f-1b31-4dcf-9561-de6c48352d83)

_Content_
![image](https://github.com/lukeorth/poison/assets/35306887/84b45cc1-6e9e-4fb6-a0d7-fea463261c0b)
