### ISSUE TITLE
Mermaid diagrams are hard to read in dark mode

### ISSUE THREAD

**Issue by jaskij** [lukeorth/poison#119]
As in the title - they are hard to read, and the colors clash. Maybe it could be fixed with styling?

![image](https://github.com/lukeorth/poison/assets/1429132/f84aa5a8-0e57-4acb-8c4f-b615d6257414)

**Comment by lukeorth** [comment]
Hi, @jaskij -- thank you for pointing this out.  I actually have a couple changes I'd like to make to the Mermaid diagrams, this being one of them.  I'll try to work on this soon. :+1:

**Comment by jaskij** [comment]
I'm not a web developer, but iirc SVG can be styled with CSS? If Mermaid's output actually works for that.

**Comment by lukeorth** [comment]
Yes it looks like it can be styled with CSS.  It also appears that Mermaid offers [dark mode support](https://mermaid.js.org/config/theming.html) out of the box -- it's just a  matter of setting the right configs for it.

**Comment by jaskij** [comment]
So it's just a matter of implementing this

**Comment by lukeorth** [comment]
Sorry, @jaskij  -- I finally got around to this with [this PR](https://github.com/lukeorth/poison/pull/145).  

As stated in the PR, I was unsuccessful in finding a way to do this with an "onClick" event, so diagrams will only be updated on page load.  Simply toggling between light/dark mode won't activate the associated theme.  I assume this isn't too big of an issue since most users will settle on using light/dark mode and stick to it, but it's still something that I don't like and could certainly be improved.  That said, I wanted to get something out there for the time being.  Hope this helps!

**Comment by jaskij** [comment]
@lukeorth thank you very much!

As you say, the onClick part isn't critical, and it's better to have it in the current state.

One thing I'm not sure if Poison is choosing light or dark based on browser preferences. I would see it that this case works more than onClick.
