### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by valsha** [lukeorth/poison#49]
Good day. Thank you for this excellent theme!
Can you possibly add a navbar (top of the page)? 
Thank you.

**Comment by lukeorth** [comment]
Hi, @valsha - Because of the sidebar navigation menu, I don't plan to add a top navbar.  That said, you can always check out these sites for alternative themes.  Many of them do have top navbars. :slightly_smiling_face: 

- https://themes.gohugo.io/
- https://hugothemesfree.com/
- https://jamstackthemes.dev/ssg/hugo/
