### ISSUE TITLE
HasChildren = false doesn't seem to work

### ISSUE THREAD

**Issue by tgamblin** [lukeorth/poison#59]
I've got this in `config.toml`:

```toml
    menu = [
        # ... /content/about/about.md
        {Name = "About", URL = "/about/", HasChildren = false},

        # ... /content/publications/publications.md
        {Name = "Publications", URL = "/publications/", HasChildren = false},

        # ... /content/posts/introducing-poison.md
        {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 20},
    ]
```

The about page shows up ok:
<img width="1345" alt="Screenshot 2023-03-11 at 6 43 11 PM" src="https://user-images.githubusercontent.com/299842/224521255-19e0c7cc-390e-41bf-a80e-ac68cebadded.png">

But publications seems to think it should be a list:

<img width="1343" alt="Screenshot 2023-03-11 at 6 42 33 PM" src="https://user-images.githubusercontent.com/299842/224521233-89a18707-f012-4bb9-bc14-ed6a26ad1587.png">

Is this expected?

**Comment by lukeorth** [comment]
Hi @tgamblin - thank you for the question.  You should be able to resolve this issue by making the following two edits:
1. Change `.../content/publications/publications.md` to `.../content/publications/_index.md`
2. Add `layout: single` to the front matter

![image](https://user-images.githubusercontent.com/35306887/224585787-af527e62-1de5-4ba6-881b-b42e22b79740.png)

![image](https://user-images.githubusercontent.com/35306887/224585734-8f7dfd69-52ab-4512-864d-55e23036bc06.png)


The reason my `About` page doesn't do this is because I've setup a custom layout in the theme to automatically handle this type of content.  You could do something similar for your `Publications` if you want by following [these instructions](https://discourse.gohugo.io/t/how-to-create-a-custom-content-type/3504), but I find the steps above to be a bit simpler.

Let me know if this fixes things for you!

**Comment by tgamblin** [comment]
ok that works -- I guess it's weird that about is different from other pages but I see that I just missed this in the documentation.  Thanks.
