### ISSUE TITLE
No feature image for social share 

### ISSUE THREAD

**Issue by R3dy** [lukeorth/poison#74]
Great Theme!!

hey sorry if this isn’t the right place for this.  I didn’t see a link to a discord or anything.

I’ve created a simple blog using the theme
https://blog.roycedavis.net/

when I try to share a link on Twitter I don’t see an image.  Is it easy to set a feature image on posts or maybe the brand image from the nav to show up like most sites do when you share them out?
![IMG_1857](https://github.com/lukeorth/poison/assets/2473341/36b892d8-3935-498f-8c5e-c518c2d3dd8e)

**Comment by lukeorth** [comment]
Hi @R3dy - I'm glad you're enjoying the theme!

Thank you for this suggestion.  Someone else added support for this awhile back (called the [Open Graph protocol](https://ogp.me/)), but I wasn't familiar with it at the time and didn't look into it very much.  Finally decided to dive into it.

You can now add a feature image by creating an `assets` directory in the root of your project, adding images to it, and including their path in your post's frontmatter.  

For example, this is the directory structure for my Poison demo site.

![image](https://github.com/lukeorth/poison/assets/35306887/9cf759a7-de6a-42ba-9d3b-4fb9240b722e)

So I was able to enable a feature image by updating my frontmatter for the [Introducing Poison](https://poison.lukeorth.com/posts/introducing-poison/) post like so:

![image](https://github.com/lukeorth/poison/assets/35306887/8cf565e5-f3d5-4fdb-a2a8-3ae7b15d6498)

This post is now displayed on Twitter like this:

![image](https://github.com/lukeorth/poison/assets/35306887/9f65e7ea-5613-469b-bac3-14c657d98627)

I hope this helps!  Let me know if you run into any hiccups or have any questions. :+1:

**Comment by R3dy** [comment]
Hey @lukeorth  would you mind looking at this at helping me spot what I'm doing wrong?  I ran `git pull` today so I should definitely have this code (unless I'm wrong about that...)

So here you can see I have the path `/content/images` where all my images are stored.

```bash
royce@hacktop:~/hugo/roycedavis.net/content ‹main›
$ ls -lah images/post-image-001.jpg
-rw-r--r--  1 royce  staff   193K Jun 14 15:01 images/post-image-001.jpg
```

And then here is a post where I call that image in the front matter.
```bash
royce@hacktop:~/hugo/roycedavis.net/content ‹main›
$ head posts/smarter-than-an-ai.md
---
title: "Are You Smarter Than an AI"
date: "2023-06-14"
image: "/images/post-image-001.jpg"
---
```

However I'm still not seeing the feature image on social media.
![Screenshot 2023-06-14 at 4 28 44 PM](https://github.com/lukeorth/poison/assets/2473341/5c744fcd-097e-47d2-a216-9b3cb9c55cad)

**Comment by lukeorth** [comment]
Hey, @R3dy -- I'm sorry to hear it's not working for you. I think I know how to fix it though.

In order for Hugo to pull the images, they need to be placed in a directory called `assets` at the root of your project. If you don't already have that directory (it's possible you don't) then you'll need to create it and put your images there. You can create subdirectories within `assets` too if you want more organization, meaning you could store your image at a location like `assets/smarter-than-ai/post-image-001.jpg`. But it won't work if your images are stored in the `content` or `static` directories.

Also, because it's required that your images be in `assets`, you don't need to include that directory name in your front matter's image path. So an image stored at `/assets/smarter-than-ai/post-image-001.jpg` would be referenced in your front matter like this:

```
---
title: "Are You Smarter Than an AI"
date: "2023-06-14"
image: "smarter-than-ai/post-image-001.jpg"
---
```

I hope that helps! Let me know if you have any more issues though.
